### ISSUE TITLE
Autosave in gang wars and during some missions

### ISSUE THREAD

**Issue by bozata** [gta-chaos-mod/Trilogy-ASI-Script#103]
So, today i got to the mission doberman, and when i got to the 3rd wave it said Autosaving... but it never completed which meant i had to do the whole mission again, also on los septucolos i believe, there is an autosave trigger at the start that also never completes. Btw is it possible to implement autosaving in the middle of longer missions so you don't have to do the whole mission again if you fail? Something like improvised checkpoints

**Comment by Lordmau5** [comment]
Doberman autosaving is a side-effect of the horrible "AutosaveAfterGangWar" config setting, so just ignore that mission in particular.
That feature was implemented so speedrunners (or just normal players as well) wouldn't have to restart from scratch when taking over the 18 or so gang territories at the end of the game.

Instead, I highly recommend disabling that feature and enabling the `SkipGangTerritoriesCheck` option, which will make it so you don't have to complete gang territories at all for Los Desperados.

As for saving within missions, that's pretty much impossible due to not being able to consistently storing the mission state.
