### ISSUE TITLE
Trilogy?

### ISSUE THREAD

**Issue by BuoYancYdabl** [gta-chaos-mod/Trilogy-ASI-Script#138]
Since there is GTA Degradition Edition is this mod for default GTA SA? Or the TRILOGY DEFINITIVE EDITION?

**Comment by Frouk3** [comment]
for not definitive

**Comment by Lordmau5** [comment]
Yeah the mod is for the original games.

While I am still interested in potentially adding support to the definitive editions of 3 and VC (since those are actually playable and, in my opinion, enjoyable), I will probably not touch SA definitive edition. It's an atrocity originating from a dumpster fire and should have been sent to hell instead of storefronts.

Though, the lack of a SDK for those definitive editions makes it super difficult trying to make anything for them.
