### ISSUE TITLE
Vehicle setHealth tip

### ISSUE THREAD

**Issue by Frouk3** [gta-chaos-mod/Trilogy-ASI-Script#140]
https://github.com/gta-chaos-mod/Trilogy-ASI-Script/blob/ff32ec055d6032aa80c5aba0d491383f55bfe32c/src/gtasa/effects/cheats/player/HealthArmorMoneyCheat.cpp#L27

if you wanna, you can replace it like this:

```
float setHealth = max(1000.0f,vehicle->m_fHealth) //math.max
```

**Comment by Lordmau5** [comment]
There's a reason it's coded the way it is.

By default vehicles only have a max health of 1000.0f which means it should set it to that.

Some mission vehicles have higher health and setting those to 1000.0f caused some of them to explode, which is why I check if their health is above 1000.0f and will set it to 100k health instead.
