### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Ancend7** [gta-chaos-mod/Trilogy-ASI-Script#141]
When upside-down, mirrored world and mirrored screen is active.

**Comment by Lordmau5** [comment]
What GPU do you have?

**Comment by Ancend7** [comment]
An Intel(R) HD Graphics

**Comment by Lordmau5** [comment]
From what I've heard this was fixed in-dev for the v3.0 rework.

However, I can't give an ETA on when it will be released as the mod will pretty much be rewritten from scratch :(

One idea I would have is to get you a custom version of the current mod built so you can test if the fix actually works if you are interested?
In which case, would you be so kind as to send me a Discord friend request? - Lordmau5#0001

**Comment by Lordmau5** [comment]
Should be fixed in v3.0.1
