### ISSUE TITLE
Bugs in few effects and few options in-GUI or mod

### ISSUE THREAD

**Issue by Kristof-30** [gta-chaos-mod/Trilogy-ASI-Script#142]
After playing thousands hours in your mod I noticed few bugs (which probably some of them are intended to be like that) and I see you are working on mod again so I decided to write it (even these you probably know):

- [x] 1.Random Teleport is randomly crashing sometimes
- [x] 2.Fail Current Mission in-cutscene is softlocking the game, and you have to use task manager to shutdown the game to play it again
- [x] 3.All Taxis Have Nitrous deletes the rewarded Nitro after completing 50 fares (probably it happens after the effect ends)
- [x] 4.Connecting 2x Game Speed or 4x Game Speed or Powerpoint Presentation with Quadruple Gravity makes some cars shaking very hardly
- [x] 5.Peds Attack You or Peds Attack Each Other or Have A Bounty On Your Head + Clear Active Effects is only clearing them once and after mission ends 1 of these effects is enabled again
- [x] 6.When you start a mission and Get Busted or Wasted 1 second after, the game crashes
- [x] 7.Pop Tires Of All Vehicles is not working on Quadbike but To Drive Or Not To Drive is working on it
- [x] 8.Invisible Vehicles (Only Wheels) adds 7th wheel in middle of both sides of Rhino tank
- [x] 9.Invisible Vehicles still shows 4 wheels of Rhino in both sides, planes/helicopters are not affected with this effect
- [x] 10.Saving with Timelapse Mode enabled, and roading the save after the effect ends makes infinite timelapse mode (can be canceled after getting it again and let it end, and save after that or by autosaves and quicksaves)
- [x] 11.Saving with Long Live The Rich and loading save will only save your current money health instead of all money hiding without the effect, (can be avoided with autosaves and quicksaves), but after getting this second time when it was already enabled and letting it go will give you random money instead of your current money
- [x] 12.Ghost Rider in mission "Wear Flowers In Your Hair" is exploding the car at start of mission where you have to get inside the car
and in Trucking missions makes the rig blow up
- [x] 13.Force Vehicle Mouse Steering in weaker PC's (not mine) makes the game instantly crash (noticed this while playing gta:sa on pendrive in school)
- [x] 14.1. Connecting Upside-Down Screen or Mirrored Screen or Tunnel Vision or DVD Screensaver
- [x] 14.2. and Clear Active Effects
- [x] 14.3. and third effect has to be the same from 14.1. you got before, will be not functioning after effect from 14.1 disappear from list
- [x] 15. Pedal To The Metal can be avoided by pressing Brakes button + Leaving Car button
- [x] 16. Inverted Controls makes fast sliding impossible (CJ slides with normal walking speed)
- [x] 17. Enabling any of first three expertimentals in GUI disables possibility of normal chat voting with twitch chat voting messages as written option 1,2,3 will not be given to the game
- [x] 18. Enabling Twitch Anarchy Mode and disabling 3x cooldowns and writing RingRing command will give Ring Ring !! for 30 seconds instead of 15 seconds and will disappear from list after 15 seconds and make the player stuck in phone

And that's probably all I found I will comment in this issue more bugs when I will find/remember them

**Comment by Lordmau5** [comment]
Okay that's a long list, let's see what I can say about all of these:

1. I'll investigate that, though I wouldn't know how to track down the issue without any logs and probably not being able to reproduce it myself.

2. Softlocking in cutscene? Which type of cutscene, a normal ingame one or a fully animated one?

3. I'll have to look into it, though won't be able to promise anything about this

4. Not interested in looking into this, it's a side-effect I guess

5. Should be fixed with the rewrite

6. Should be fixed with the rewrite, will look into it again once that's done though

7. Should be fixed with the rewrite

8. Will investigate, though not sure what I'm looking for. Can you provide a screenshot of it maybe?

9. Same as with 9, screenshots would be nice

10. Will need to hook the game's save process and temporarily set the corresponding value for it

11. Same as with 10

12. Don't do "Wear Flowers In Your Hair" or trucking missions in that case - I'm not gonna add special handling for missions unless I *have to*

13. You're the first to report this so I'm not gonna be looking into this. Don't play from a pendrive I guess.

14. Should be fixed with the rewrite... Though I can't quite follow what you're trying to say

15. Will investigate

16. I remember one streamer was able to still slide at... well, sliding speed when they had Inverted Controls enabled - I also remember the same for me. So not gonna look into that until more people will report issues with it.
Alternatively: Don't slide with Inverted Controls

17. They are experimental for a reason, also I don't think 1 and 2 were meant for Twitch interaction.
When Twitch Anarchy is enabled you don't even need to start the timer if I remember correctly - the effects will get enabled immediately.

18. See 17 for Twitch Anarchy explanation

**Comment by Lordmau5** [comment]
Freefall crashing in interior was already reported in #107 and I could reproduce it just now, it'll be fixed in the rewrite :)

2. Yeah, so motion capture cutscenes... And okay, I'll need to look into that then

3. I remember seeing a video about this 7th set of wheels being hidden by default, need to see if I can exclude them. It's not a ... game-breaking bug though, so I'd say it's lower priority

9. Need to look into that

13. Talked with Parik about it, he said he experienced something similar... So yeah, will look into it

14. *Should* be fixed in the rewrite

17. Yeah, but they're marked as "Experimental" for a reason. No support given for those.

**Comment by Lordmau5** [comment]
11. Was fixed in-dev just now as well (Saving with Long Live The Rich)

**Comment by Kristof-30** [comment]
That's good!
I also forgot about 2 low priority bugs:
1. Random Teleport is enabled in rapid-fire even tho effect list document shows it disabled.
2. Picking Adrenaline pickup (the slow motion pill you can get in rainbomizer) with enabled 4x Game Speed or 2x Game Speed or 0.5x Game Speed or Experience The Lag will make this effects timers go much faster (example: 8 seconds per 1 second in 4x and 2x game speed)

**Comment by Lordmau5** [comment]
Regarding 12 in the list, this is part of the "Wear Flowers In Your Hair" mission script
![image](https://user-images.githubusercontent.com/1345036/168824928-6d24be96-895f-46a2-a43d-b6a7293cf5b3.png)

As you can see, the game is checking if the car is burning (which it obviously is), and if that's the case, it just blows it up.
Thanks, Rockstar.

**Comment by Lordmau5** [comment]
I managed to somehow get this working, although not perfect.

So I've hooked the opcode for `Is Car On Fire` and, when that mission is active, it'll return `0`.
Now, that means it'll return `0` for **all** vehicles in that mission. A small price to pay for not getting instantly blown to pieces I'd say.

**Comment by Lordmau5** [comment]
Okay, let me recap all the issues:

> Random Teleport is randomly crashing sometimes

Fixed

> Fail Current Mission in-cutscene is softlocking the game, and you have to use task manager to shutdown the game to play it again

Fixed

> All Taxis Have Nitrous deletes the rewarded Nitro after completing 50 fares (probably it happens after the effect ends)

Fixed

> Connecting 2x Game Speed or 4x Game Speed or Powerpoint Presentation with Quadruple Gravity makes some cars shaking very hardly

This *might* be fixed with the way gravity is being handled in the v3.0 rewrite, but I don't consider this a high priority.

> Peds Attack You or Peds Attack Each Other or Have A Bounty On Your Head + Clear Active Effects is only clearing them once and after mission ends 1 of these effects is enabled again

Should be fixed

> When you start a mission and Get Busted or Wasted 1 second after, the game crashes

Fixed

> Pop Tires Of All Vehicles is not working on Quadbike but To Drive Or Not To Drive is working on it

Fixed

> Invisible Vehicles (Only Wheels) adds 7th wheel in middle of both sides of Rhino tank

Fixed

> Invisible Vehicles still shows 4 wheels of Rhino in both sides, planes/helicopters are not affected with this effect

Fixed

> Saving with Timelapse Mode enabled, and roading the save after the effect ends makes infinite timelapse mode (can be canceled after getting it again and let it end, and save after that or by autosaves and quicksaves)

Fixed

> Saving with Long Live The Rich and loading save will only save your current money health instead of all money hiding without the effect, (can be avoided with autosaves and quicksaves), but after getting this second time when it was already enabled and letting 
it go will give you random money instead of your current money

Fixed

> Ghost Rider in mission "Wear Flowers In Your Hair" is exploding the car at start of mission where you have to get inside the car

Fixed

> and in Trucking missions makes the rig blow up

Fixed

> Force Vehicle Mouse Steering in weaker PC's (not mine) makes the game instantly crash (noticed this while playing gta:sa on pendrive in school)

Not reproducable, though it might work better now. Please try again once the mod is out if you get a chance.

> Pedal To The Metal can be avoided by pressing Brakes button + Leaving Car button

Not sure this is easily fixable. It's still making driving more difficult so I'll leave it be for now.

> Inverted Controls makes fast sliding impossible (CJ slides with normal walking speed)

Side-effect I guess? No idea.

> Enabling any of first three expertimentals in GUI disables possibility of normal chat voting with twitch chat voting messages as written option 1,2,3 will not be given to the game

Those experimental options were removed.

> Enabling Twitch Anarchy Mode and disabling 3x cooldowns and writing RingRing command will give Ring Ring !! for 30 seconds instead of 15 seconds and will disappear from list after 15 seconds and make the player stuck in phone

Twitch Anarchy Mode was removed. It was only really used for testing.
