### ISSUE TITLE
Another bug report + some suggestions

### ISSUE THREAD

**Issue by Kristof-30** [gta-chaos-mod/Trilogy-ASI-Script#297]
1. Recruit Anyone (Spraycan) is not working because it has effect ID mistaken in GUI code:
Current effect ID: recruit_anyone_spraycan
in .asi file code it's: recruit_anyone_spray
2. Lock All Garages can permamently lock your garages when you save with this effect enabled, then wait for effect to end and load the save you saved. It fixes itself if you get this effect again and effect ends.
3. LIDL Rapid-Fire sound is not working even if it's sound effect is already in files after the mod is downloaded.
4. Death's sound effect name is not changed (it's still effect_suicide insted of effect_death), I know we can change it ourselves but still wanted to report that so you could maybe change it if you want to.
5. Fake Get Wasted/Busted to look more like they regular Get Wasted/Busted should disable radio stations for these few seconds like regular ones have, and have the same sound effect the regular versions have by default, I know we can put those ourselves but still it could be here by default to fool anyone who just downloaded this version (Sorry If I messed up English here)
6. If you uncomment Give NPC's A Spray Or Fire Extinguisher in GUI code and compile it, the .exe does not open at all. I don't know if it's because I used debug but wanted you to know. Also suggestion for the shorter name: "Give NPCs Spray/Fire Ex" and then display game name the regular "Give NPC's A Spray Or Fire Extinguisher"

**Comment by Lordmau5** [comment]
Just gonna respond to this already on a whim

1. Oversight, will be fixed in the next version (Maybe end of week, no promises though)
2. Probably able to fix as well by disabling it in the hooked "save" method (where the mod already disables some cheats if I remember correctly)
3. Hmm weird, I'll look into that in the coming days, too
4. Not that urgent but thanks for the heads-up - should be easily fixable, too
5. Not that urgent either in my opinion - it's meant to catch people off-guard and in the moment they'll probably not think too much about it. If someone wants to PR that into the effect then I can add it :)
6. Not sure why it wouldn't compile - As for the name, I'd rather not have a super long name ingame (nor for the chat / poll voting), so it'll stay commented out for now

**Comment by Lordmau5** [comment]
1. Fixed in-dev
2. Can't think of a good and easy way to get an instance for an effect so I'd suggest not saving with the effect active
3. That's because the sound would need to be played from the GUI again, which has been removed. Instead I'll be removing `LIDL Rapid-Fire` as a whole since it doesn't really do anything anymore (besides another effect)
4. Fixed in-dev
5. As said, not that urgent so I'll leave it "unfixed" for now
6. As mentioned before, still not a good name for it

**Comment by Lordmau5** [comment]
Hmm... Actually, `LIDL Rapid-Fire` will be back in. I was a bit too quick on axing it but I managed to find a good way to implement it again while still playing the sound from the game itself.

So yeah, next version in that case lmao
