### ISSUE TITLE
[New Effect] All traffic is *insert vehicle here*

### ISSUE THREAD

**Issue by Lebon14** [gta-chaos-mod/Trilogy-ASI-Script#34]
Self-explanatory. However, there are a LOT of vehicles in the game according to this page:
https://www.grandtheftwiki.com/Vehicles_in_GTA_San_Andreas

So, we could have 1 effect per vehicle category excluding flying vehicles.
And a couple of effects for specific cars:
- Infernus
- Bobcat
- Slamvan
- Jester
- Virgo
- Admiral
- Ambulance
- Barracks
- Enforcer
- Fire Truck
- Police Car
- Rhino
- S.W.A.T Tank
- Caddy
- Journey
- Kart
- Monster
- The Mothership
- Mower
- Quad
- Vortex
- HPV-1000
- Faggio
- Pizzaboy
- Bike / BMX / Mountain Bike
- Bus
- Cabbie / Taxi
- Forklift
- Tow Truck
- Trashmaster
- Hot Dog
- Mr Whoopee
- Cement Truck
- Combine Harvester
- Dozer
- Dumper
- Tractor

I realize that is a lot of cars. Either we choose the memest of meme cars (such as caddie) and make a much smaller list (less than 10 cars) *or* allow a 2nd cheat to activate at the same time as this particular one.

**Cheat Code name:** (varies for each car / category of car)
**Recommanded lengths:**
**Easy:** 180 seconds
**Normal:** 180 seconds
**Hard:** 180 seconds
**Chaos:** 180 seconds

(Threads done as requested by Lordmau5)

**Comment by Lordmau5** [comment]
I've fiddled around a bit with it and was semi-successful.

Had some crashes here and there but I do think this could become a few separate effects (which would, obviously, cancel each other out since they'd be the same type in the end)

I'd also probably only take a few of the good ones of that list, such as Infernus, Bobcat, Caddy, Rhino and the Mower.
Not final of course, but effects for ALL of them would be crazy, and not all of them would be... good, I'd say (such as the Jester, Virgo and a few more)

**Comment by Lordmau5** [comment]
Added a couple of those in v3.0.1, though they can cause the game to crash in certain scenarios. Use with care.
