### ISSUE TITLE
BUG with mirrored screen and world

### ISSUE THREAD

**Issue by kruzgi** [gta-chaos-mod/Trilogy-ASI-Script#75]
![chaosmodbug](https://user-images.githubusercontent.com/57067715/76900930-90b11c80-689a-11ea-8a85-e648c9ef8077.png)
When i get mirrored world or mirrored screen effect i see 2 triangles on my screen

**Comment by DrPhilPerlmutter** [comment]
Same issue for me.

**Comment by Lordmau5** [comment]
This is because you guys are running AMD graphics cards (or maybe integrated graphics from your CPU)

As I didn't do this effect (same with Upside-Down Screen) and don't have an AMD card to test it with I will not be working on a fix for this.

The code for the mod is available to the public so if someone wants to look into this issue they're free to do so.

**Comment by Dragas** [comment]
Perhaps atleast add disclaimer that it does not work with AMD GPUs?
