### ISSUE TITLE
Pass current mission doesn't work

### ISSUE THREAD

**Issue by Beteoto** [gta-chaos-mod/Trilogy-ASI-Script#80]
I had an issue with this effect in GTA San andreas, it doesn't pass the mission, actually does nothing, the mission was still on. I tried with Robing Uncle Sam, Wrong side of the tracks and Just Business and nothing, the effect wasn't working.

**Comment by Lordmau5** [comment]
Make sure you are on v1.0 of the game (the executable should be roughly 14MB in size)

If that is not the case, downgrade again.

If that also does not help then see #57 - someone else had a similar issue so maybe that could work for you, too.

**Comment by Beteoto** [comment]
I uninstalled the game and reinstalled, it worked a few times and then the problem got back

**Comment by Parik27** [comment]
There's an issue with some downgraders that don't downgrade the main.scm with it, so you're left with a main.scm different from the one in 1.0. I assume the Pass Current Mission effect depends on the v1 main.scm, since it has hardcoded offsets that probably don't work on other main.scm versions. 

To check if you have the correct main.scm version, you could check the size of main.scm (in data/script/) and make sure it's 3079599 bytes.

**Comment by Beteoto** [comment]
I already have the 1.0 version of the game, it's a cracked version (In the installer it says is 1.0.0)

**Comment by Lordmau5** [comment]
I don't give support for people that didn't buy the game.
